# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: 127.0.0.1 (MySQL 5.6.21)
# Database: hipaadev
# Generation Time: 2015-12-03 15:33:52 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table clients
# ------------------------------------------------------------

LOCK TABLES `clients` WRITE;
/*!40000 ALTER TABLE `clients` DISABLE KEYS */;

INSERT INTO `clients` (`partner_id`, `name`, `email`, `account_type`, `active`, `demo`, `display_ra_org`, `display_intro_video`, `admin_account`, `user_account`, `details`, `file_key`, `last_login`, `risk_assessment_status`, `created`, `modified`, `moodle_course_id`, `moodle_course_name`)
VALUES
	(NULL,'HIPAA','','HIPAA',1,0,'1',1,'','','','','2015-12-03 10:11:55','2014-07-10','2012-12-10 07:34:20','2015-12-03 10:11:55',30,'HIPAA-105');

/*!40000 ALTER TABLE `clients` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table education_center
# ------------------------------------------------------------



# Dump of table groups
# ------------------------------------------------------------

LOCK TABLES `groups` WRITE;
/*!40000 ALTER TABLE `groups` DISABLE KEYS */;

INSERT INTO `groups` (`id`, `name`, `created`, `modified`)
VALUES
	(1,'Administrators','2012-12-10 07:34:36','2012-12-10 07:34:36'),
	(2,'Managers','2012-12-10 07:34:42','2012-12-10 07:34:42'),
	(3,'Users','2012-12-10 07:34:52','2012-12-10 07:34:52'),
	(4,'Pending','2013-02-03 18:00:15','2013-02-03 18:00:15');

/*!40000 ALTER TABLE `groups` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table risk_assessment_question_safeguard_categories
# ------------------------------------------------------------

LOCK TABLES `risk_assessment_question_safeguard_categories` WRITE;
/*!40000 ALTER TABLE `risk_assessment_question_safeguard_categories` DISABLE KEYS */;

INSERT INTO `risk_assessment_question_safeguard_categories` (`id`, `name`)
VALUES
	(1,'Administrative'),
	(2,'Physical'),
	(3,'Technical');

/*!40000 ALTER TABLE `risk_assessment_question_safeguard_categories` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table risk_assessment_question_sub_categories
# ------------------------------------------------------------

LOCK TABLES `risk_assessment_question_sub_categories` WRITE;
/*!40000 ALTER TABLE `risk_assessment_question_sub_categories` DISABLE KEYS */;

INSERT INTO `risk_assessment_question_sub_categories` (`id`, `name`, `video_name`, `safeguard_category_id`)
VALUES
	(1,'Security Management','',1),
	(2,'Business Associates','',1),
	(3,'Contingency Planning','',1),
	(4,'Information Access','',1),
	(5,'Security Response','',1),
	(6,'Security Awareness','',1),
	(7,'Facility Access Control','',2),
	(8,'Workstation Security','',2),
	(9,'Device and Media Control','',2),
	(10,'Password Control','',3),
	(11,'Audit Controls','',3),
	(12,'Encryption','',3),
	(13,'Access Control','',3);

/*!40000 ALTER TABLE `risk_assessment_question_sub_categories` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table risk_assessment_questions
# ------------------------------------------------------------

LOCK TABLES `risk_assessment_questions` WRITE;
/*!40000 ALTER TABLE `risk_assessment_questions` DISABLE KEYS */;

INSERT INTO `risk_assessment_questions` (`id`, `question_number`, `category_question_number`, `category_id`, `safeguard_category_id`, `question`, `additional_information`, `how_to_answer_question`, `video_name`)
VALUES
	(1,1,31,10,3,'Do employees protect passwords and do not share with other employees?','<p>When accessing ePHI every member of the workforce must use an unique userid and password. Workforce members should not share passwords with each other. This includes leaving passwords in plain sight, posting them on notes and sticking them to the monitor, leaving passwords written under the keyboard, etc.</p>\r\n','<p>Answer &quot;YES&quot; if workforce members protect userids and passwords and do not share userids and passwords.</p>\r\n\r\n<p>Answer &quot;NO&quot; if workforce members use shared userids and passwords or if workforce members at times share userids and passwords among themselves or if workforce members post passwords on monitors or under keyboards.</p>\r\n','RAQPW1'),
	(2,2,32,10,3,'Are workforce members required to create a complex password?','<p>A complex password, sometime known as a strong password is a password that consists of at least six characters (and the more characters, the stronger the password) that are a combination of letters, numbers and symbols (@, #, $, %, etc) if allowed. Passwords are typically case-sensitive, so a complex password contains letters in both uppercase and lowercase. Complex passwords also do not contain words that can be found in a dictionary or parts of the users own name.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented procedures to require workforce members to create complex passwords for all systems that contain ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if workforce members are allowed to use non-complex passwords.</p>\r\n','RAQPW2'),
	(3,3,33,10,3,'Are workforce members required to change their passwords periodically?','<p>Requiring workforce members to change passwords every 30 or 60 or 90 days will help secure their user account. Password changes prevent breached accounts from being access over a long period of time.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has procedures in place that require workforce members to change their passwords on a periodic basis for all systems that contain ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have procedures in place that require workforce members to change their passwords on a periodic basis.</p>\r\n','RAQPW3'),
	(4,4,34,10,3,'Will workforce member accounts get disabled or locked if they mistype or incorrectly put in their password numerous times?','<p>Disabling or locking user accounts protects user accounts from being compromised. Hackers, either human or malware, usually try to guess passwords or use brute force programs to continually try to guess a password. By disabling accounts after a certain number of failed passwords attempts it makes it extremely difficult for hackers to compromise accounts.</p>\r\n','<p>Answer &quot;YES&quot; if workforce members accounts get disabled or locked after failed password attempts for all systems that contain ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if workforce members accounts do not get disabled or locked after failed password attempts.</p>\r\n','RAQPW4'),
	(5,5,35,11,3,'Does the organization have system auditing setup to facilitate the detection of unauthorized access?','<p>The HIPAA Security Rule requires that all access to ePHI be logged or audited. Information that is usually collected is: Who is the person or userid that is accessing ePHI? When did the person or userid access ePHI? What ePHI was accessed? EMRs, network shares and other server based systems need to have system auditing setup and configured.</p>\r\n','<p>Answer &quot;YES&quot; if the organization does have system auditing setup.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have system auditing setup.</p>\r\n','RAQSA'),
	(6,6,36,11,3,'Does the organization, on a regular basis review audit logs?','<p>The HIPAA Security Rule requires that system audit logs be periodically reviewed to ensure that only appropriate access to ePHI is occurring. The review would ensure that only appropriate userids are accessing ePHI and that the userids are only accessing the ePHI that they are authorized to access. Regular review of system audit logs can detect data breaches and unauthorized access to ePHI.</p>\r\n','<p>Answer &quot;YES&quot; if the organization does review audit logs.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a procedure to review audit logs.</p>\r\n','RAQSAR'),
	(7,7,5,2,1,'Have your Business Associates signed Business Associate agreements?','<p>HIPAA defines a &quot;Business Associate&quot; as: A person or entity that performs certain functions or activities that involve the use or disclosure of protected health information on behalf of, or provides services to, a covered entity. The HIPAA Security Rule requires that all Business Associates have signed agreements with covered entities (i.e. practices) stating that they will protect ePHI and comply with the HIPAA Security Rule.</p>\r\n','<p>Answer &quot;YES&quot; if all your Business Associates have signed Business Associate agreements.</p>\r\n\r\n<p>Answer &quot;NO&quot; if all your Business Associates have not signed Business Associate agreements.</p>\r\n','RAQBA1'),
	(8,8,6,2,1,'Have your Business Associates been trained on the HIPAA Security Rule and how to protect ePHI?','<p>In order for Business Associates to protect ePHI and to comply with the HIPAA Security Rule, they need to understand the HIPAA Security Rule. Ensuring that Business Associates are trained on the HIPAA Security Rule will help protect ePHI.</p>\r\n','<p>Answer &quot;YES&quot; if your Business Associates have been trained on the HIPAA Security Rule and protecting ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if your Business Associates have not been trained on the HIPAA Security Rule and protecting ePHI.</p>\r\n','RAQBA2'),
	(9,9,7,3,1,'Does the organization have documented disaster recovery procedures in place?','<p>The HIPAA Security Rule states the following as a requirement: (7)(i) Standard: Contingency plan. Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information. Disaster recovery plan (Required). Establish (and implement as needed) procedures to restore any loss of data.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has documented disaster recovery procedures in place and regularly test the procedures.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have documented recovery procedures in place or does not test the procedures regularly.</p>\r\n','RAQDR'),
	(10,10,8,3,1,'Does the organization have documented data backup procedures in place?','<p>The HIPAA Security Rule states the following as a requirement: (7)(i) Standard: Contingency plan. Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information. Data backup plan (Required). Establish and implement procedures to create and maintain retrievable exact copies of electronic protected health information.</p>\r\n','<p>Answer &quot;YES&quot; if the organization does have a documented and tested data backup procedure in place.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a documented data backup procedure in place or does not test the backup procedure.</p>\r\n','RAQDB'),
	(11,11,17,7,2,'Are servers protected from water damage and not located near a water source?','<p>In order to protect ePHI it is important to ensure that systems containing ePHI are protected from environmental danger. Co-locating servers containing ePHI by water sources may lead to damage or destruction of ePHI.</p>\r\n','<p>Answer &quot;YES&quot; if servers are not located near a water source.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the servers are located anywhere near a water source, Ex: water pipes going through the room, servers located near bathrooms or kitchens.</p>\r\n','RAQWD'),
	(12,12,18,7,2,'Does the organization use any methods to track who or when someone enters the room(s) where the servers are located?','<p>The HIPAA Security Rule states: &Acirc;&sect; 164.310 Physical safeguards. A covered entity must, in accordance with &Acirc;&sect; 164.306: (a)(1) Standard: Facility access controls. Implement policies and procedures to limit physical access to its electronic information systems and the facility or facilities in which they are housed, while ensuring that properly authorized access is allowed. (ii) Facility security plan (Addressable). Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft. (iii) Access control and validation procedures (Addressable). Implement procedures to control and validate a person&acirc;&euro;&trade;s access to facilities based on their role or function, including visitor control, and control of access to software programs for testing and revision. (iv) Maintenance records (Addressable). Implement policies and procedures to document repairs and modifications to the physical components of a facility which are related to security (for example, hardware, walls, doors, and locks).</p>\r\n','<p>Answer &quot;YES&quot; if the organization tracks who and when someone enters the room(s) where servers are located. Note: Servers may be located in multiple locations.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not track access to the room(s) where servers are located.</p>\r\n','RAQTSRA'),
	(13,13,19,7,2,'Is the location(s) where the organization keeps their servers locked at all times?','<p>The HIPAA Security Rule states: &Acirc;&sect; 164.310 Physical safeguards. A covered entity must, in accordance with &Acirc;&sect; 164.306: (a)(1) Standard: Facility access controls. Implement policies and procedures to limit physical access to its electronic information systems and the facility or facilities in which they are housed, while ensuring that properly authorized access is allowed. (ii) Facility security plan (Addressable). Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft.</p>\r\n','<p>Answer &quot;YES&quot; if the location(s) where the organization keeps their servers is locked at all times. Note: Servers may be located in multiple locations.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the location(s) where the organization keeps their servers is not locked at all times and the servers are accessible to workforce members, visitors, and patients.</p>\r\n','RAQLSL'),
	(14,14,20,7,2,'Does the organization restrict access to the room(s) or location where servers are located?','<p>The HIPAA Security Rule states: &Acirc;&sect; 164.310 Physical safeguards. A covered entity must, in accordance with &Acirc;&sect; 164.306: (a)(1) Standard: Facility access controls. Implement policies and procedures to limit physical access to its electronic information systems and the facility or facilities in which they are housed, while ensuring that properly authorized access is allowed. (ii) Facility security plan (Addressable). Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft. (iii) Access control and validation procedures (Addressable). Implement procedures to control and validate a person&acirc;&euro;&trade;s access to facilities based on their role or function, including visitor control, and control of access to software programs for testing and revision. (iv) Maintenance records (Addressable). Implement policies and procedures to document repairs and modifications to the physical components of a facility which are related to security (for example, hardware, walls, doors, and locks).</p>\r\n','<p>Answer &quot;YES&quot; if the organization restricts access to the room(s) or location where servers are located. Note: Servers may be located in multiple locations.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the access to the room(s) or location where servers are located is not restricted.</p>\r\n','RAQRATS'),
	(15,15,9,3,1,'Does the organization have redundancy in place for all critical systems?','<p>The HIPAA Security Rule states the following as a requirement: (7)(i) Standard: Contingency plan. Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has redundancy in place, including spare equipment, for all critical systems.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have redundancy in place including spare equipment that can be used in case of disaster or hardware failure.</p>\r\n','RAQSR'),
	(16,16,10,3,1,'Does the organization have redundant data circuits in place in case of circuit failure?','<p>The HIPAA Security Rule states the following as a requirement: (7)(i) Standard: Contingency plan. Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information. An outage of a data circuit may prevent access to ePHI. Having redundant circuits such as a T-1 with a backup DSL or Cable Modem can minimize or reduce the chances of outages that can prevent access to ePHI.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has redundant data circuits in place in case of a circuit failure.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have redundant circuits in place in case of a circuit failure.</p>\r\n','RAQRDC'),
	(17,17,43,13,3,'Is the organization\'s remote access secured to prevent unauthorized access?','<p>The Department of Health and Human Services states the following about remote access to ePHI. &quot;We group some of the risks associated with remote access and offsite use of EPHI into three areas: access, storage and transmission. Risk management planning takes all three areas into account, based on the unique vulnerabilities they introduce to covered entities that rely on remote operations involving EPHI.&quot; It is critical to ensure that an organization&#39;s remote access is properly protected. Remote Access should be secure, require proper authentication and utilize encryption to protect the data.</p>\r\n','<p>Answer &quot;YES&quot; if the organization&#39;s remote access is secured to prevent unauthorized access.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the remote access is unsecured and could be susceptible to unauthorized access.</p>\r\n','RAQRAS'),
	(18,18,44,13,3,'Is the organization\'s wireless access properly secured?','<p>In order to protect ePHI from authorized access it is critical to ensure that wireless access requires authentication (proper login) and utilizes encryption to prevent ePHI from being accessed, modified or stolen. One way to tell if your organization&#39;s wireless is not secured is if visitors can bring in a laptop and connect to your wireless network without a password.</p>\r\n','<p>Answer &quot;YES&quot; if the organization&#39;s wireless connection is properly secured with encryption and authentication to prevent unauthorized access.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization&#39;s wireless connection is not properly secured with encryption and authentication and could allow unauthorized access.</p>\r\n','RAQSWA'),
	(19,19,37,12,3,'Are all the organization\'s laptops encrypted to protect the data stored on them?','<p>One of the leading causes of ePHI data breaches is lost laptops and portable media. Laptops that contain ePHI should be encrypted to prevent access to ePHI in the event a laptop if lost or stolen.</p>\r\n','<p>Answer &quot;YES&quot; if all of the organization&#39;s laptops are encrypted to protect the data stored on them.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization&#39;s laptops are not encrypted and the data is not protected in case of loss or theft.</p>\r\n','RAQEL'),
	(20,20,38,12,3,'Is backup media encrypted to protect the data?','<p>Backup media may hold a large amount of ePHI. Lost backup media could result in a large scale breach of ePHI. Ensuring that your backup media is encrypted is critical in preventing data breaches.</p>\r\n','<p>Answer &quot;YES&quot; if backup media is encrypted to protect their data.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the backup media is not encrypted and the data is not protected in case of loss or theft.</p>\r\n','RAQEBM'),
	(21,21,39,12,3,'Is portable media (USB drives, CDs, DVDs, etc) encrypted to protect the data stored on them?','<p>One of the leading causes of ePHI data breaches is lost laptops and portable media. Portable media that contains ePHI should be encrypted to prevent access to ePHI in the event the media is lost or stolen. Portable media includes USB drives, USB thumb drives, USB flash drives, CDs, DVDs, floppy drives, etc.</p>\r\n','<p>Answer &quot;YES&quot; if all portable media is encrypted to protect the data stored on them.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the all portable media is not encrypted and the data is not protected in case of loss or theft.</p>\r\n','RAQEPM'),
	(22,22,40,12,3,'Does the organization encrypt email to protect ePHI and important information sent through email?','<p>The security risks for email commonly include unauthorized interception of messages en route to recipient and messages being delivered to unauthorized recipients. These risks in using the Internet are addressed in the Security Rules technical safeguards section, particularly: - Person or Entity Authentication required procedures must be implemented for identification verification of entity or party requesting access to PHI. This means the identity of the person seeking information must be confirmed within the information system being utilized. - Transmission Security addressable data integrity controls and encryption reasonable and appropriate safeguards. All ePHI sent via email should be encrypted.</p>\r\n','<p>Answer &quot;YES&quot; if the organization implements a procedure to encrypt email to protect ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not implement or enforce a procedure that requires encryption for all email to protect ePHI and important data sent through email.</p>\r\n','RAQEE'),
	(23,23,41,12,3,'Are smartphones encrypted to protect ePHI data stored on them?','<p>Smartphones include Blackberries, iPhones, Android phones, etc. Smartphones may contain ePHI (in emails, attachments, spreadsheets, documents, etc.). Smartphone like laptops and portable media are easily lost or stolen. It is critical to ensure that all ePHI on smartphones are encrypted to prevent access to ePHI in the event the phone is lost.</p>\r\n','<p>Answer &quot;YES&quot; if the organization implements a procedure to encrypt all smartphones to protect data stored on them.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a procedure to encrypt all smartphones to protect the data.</p>\r\n','RAQES'),
	(24,24,42,12,3,'Does the organization encrypt all devices that store ePHI?','<p>Encryption is the best way to protect ePHI in the event the device is lost or stolen. Devices include laptops, portable media, desktops, and even servers. Each of the devices might be stolen in the event of a theft or break-in.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has a procedure to encrypt all devices that store ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a procedure to ensure all devices that store ePHI are encrypted.</p>\r\n','RAQEAD'),
	(25,25,13,4,1,'Is there a procedure in place to facilitate proper ePHI access being granted?','<p>The HIPAA Security Rule - Information Access Management Standard states that all users that access ePHI must have the proper authority. Initial access to ePHI must be granted (i.e. to a new workforce member) and periodic review of access must be performed. Any changes in job functions should result in a review of the person&#39;s access to ePHI. Upon termination a person&#39;s access to ePHI should be immediately revoked.</p>\r\n','<p>Answer &quot;YES&quot; if there is a procedure or policy in place that facilitates and verifies proper ePHI access is being granted to appropriate members.</p>\r\n\r\n<p>Answer &quot;NO&quot; if there is not a procedure or policy that facilitates or verifies that ePHI access is being granted to the proper workforce members.</p>\r\n','RAQFPA'),
	(26,26,22,8,2,'Are workforce members aware of workstation use policies that prohibit online activities such as email, social networks, etc.?','<p>The HIPAA Security Rule states that all workforce members should be made aware of proper workstation use. Workstation use: Implement policies and procedures that specify the proper functions to be performed, the manner in which those functions are to be performed, and the physical attributes of the surroundings of a specific workstation or class of workstation that can access electronic protected health information.</p>\r\n','<p>Answer &quot;YES&quot; if workforce members have been made aware of what is allowed or not allowed in regards to posting or mentioning ePHI. Would they know that posting ePHI data on a social network would be prohibited?</p>\r\n\r\n<p>Answer &quot;NO&quot; if workforce members have not been informed of ePHI data restrictions and would be unaware that posting ePHI on a social network would be prohibited.</p>\r\n','RAQWUP1'),
	(27,27,23,8,2,'Are workforce members advised on what is a permitted use of a workstation, are they required to sign off on that?','<p>The HIPAA Security Rule states that all workforce members should be made aware of proper workstation use. Workstation use. Implement policies and procedures that specify the proper functions to be performed, the manner in which those functions are to be performed, and the physical attributes of the surroundings of a specific workstation or class of workstation that can access electronic protected health information.</p>\r\n','<p>Answer &quot;YES&quot; if workforce members are advised and instructed on what is permiited use of a workstation, what is not allowed use and are they required to sign off that they have been informed of what is allowed use.</p>\r\n\r\n<p>Answer &quot;NO&quot; if workforce members are not advised or instructed on what they are allowed and not allowed to do on a workstation.</p>\r\n','RAQWUP2'),
	(28,28,28,9,2,'Does the organization track the movement and ownership of portable media?','<p>One of the leading causes of ePHI data breaches is lost laptops and portable media. Portable media that contains ePHI should be tracked and records maintained of the movement of all portable media. Portable media includes USB drives, USB thumb drives, USB flash drives, CDs, DVDs, floppy drives, etc. The HIPAA Security Rule states: Standard: Device and media controls. Implement policies and procedures that govern the receipt and removal of hardware and electronic media that contain electronic protected health information into and out of a facility, and the movement of these items within the facility. Accountability (Addressable). Maintain a record of the movements of hardware and electronic media and any person responsible therefore.</p>\r\n','<p>Answer &quot;YES&quot; if the organization tracks the movement (in and out of an organization) and ownership of portable media and if records are kept with this information.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not track movement or ownership of portable media and records of this are not kept.</p>\r\n','RAQTPD'),
	(29,29,29,9,2,'Does the organization have a procedure for the disposal of electronic media that stores ePHI?','<p>Media that contains ePHI must be properly disposed of. All ePHI must be removed prior to disposing. Simply deleting the ePHI from the media is not enough to safeguard the data. Special programs that totally eliminate the data from the media must be used. The HIPAA Security Rule states: Disposal (Required). Implement policies and procedures to address the final disposition of electronic protected health information, and/or the hardware or electronic media on which it is stored. Media re-use (Required). Implement procedures for removal of electronic protected health information from electronic media before the media are made available for re-use.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has a documented procedure for steps to follow for the disposal of electronic media that stores ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not document a procedure to be followed when disposing of electronic media that stores ePHI.</p>\r\n','RAQDP'),
	(30,30,30,9,2,'Do workforce members with laptops take the system home, or out of the office?','<p>One of the leading causes of ePHI data breaches is lost laptops and portable media. Laptops that contain ePHI should be tracked and only authorized workforce members should be allowed to remove them from an organization&#39;s offices.</p>\r\n','<p>Answer &quot;YES&quot; if workforce members take laptops out of the office at anytime.</p>\r\n\r\n<p>Answer &quot;NO&quot; if workforce members laptops are never removed from the organization.</p>\r\n','RAQTLOO'),
	(31,31,14,4,1,'Is there a documented and adhered to procedure for terminating a workforce member\'s access including physical network and data access?','<p>It is important to implement procedures that remove physical, network and data access to all workforce members when their employment is terminated. The HIPAA Security Rule states: Standard: Workforce security. Implement policies and procedures to ensure that all members of its workforce have appropriate access to electronic protected health information, as provided under paragraph (a)(4) of this section, and to prevent those workforce members who do not have access under paragraph (a)(4) of this section from obtaining access to electronic protected health information. Termination procedures (Addressable). Implement procedures for terminating access to electronic protected health information when the employment of a workforce member ends.</p>\r\n','<p>Answer &quot;YES&quot; if there is a documented and followed procedure for terminating a workforce member. Does the procedure cover removing all access and ID&#39;s from all systems in a timely manner?</p>\r\n\r\n<p>Answer &quot;NO&quot; if there is not an actual documented procedure that is to be followed in the event of a workforce member termination or if the procedure is not performed on a constant or timely basis.</p>\r\n','RAQTP'),
	(32,32,15,5,1,'Does the organization have an incident response procedure to follow in the event of a security breach?','<p>Organizations should be prepared in the event of a data breach containing ePHI. There should be a detailed procedure on the steps that should be taken in the event of a breach. The procedure should include the steps to respond to the breach and breach notification procedures. The HIPAA Security Rule states: Standard: Security incident procedures. Implement policies and procedures to address security incidents. Response and Reporting (Required). Identify and respond to suspected or known security incidents; mitigate, to the extent practicable, harmful effects of security incidents that are known to the covered entity; and document security incidents and their outcomes.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has a documented incident response procedure to follow in the event of a security breach. A documented procedure that outlines the steps to be taken if a security breach occurs.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a documented procedure for handling security breaches.</p>\r\n','RAQIRP'),
	(33,33,25,8,2,'Are all systems and servers fully patched for OS vulnerabilities and updated with all required application updates and service packs?','<p>Hackers and malware exploit system vulnerabilities in operating systems (Windows XP, Vista, 7 and 2003 and 2008 Server) as well as applications such as Adobe Acrobat and Microsoft Office. It is important to keep all operating systems and applications up to date with security patches.</p>\r\n','<p>Answer &quot;YES&quot; if you have an implemented procedure for patching all systems\\servers with required application and OS updates.</p>\r\n\r\n<p>Answer &quot;NO&quot; if you do not have an implemented procedure for keeping all systems\\servers updated with the required application and OS updates.</p>\r\n','RAQPATCHING'),
	(34,34,26,8,2,'Is anti-malware (anti-virus and anti-spyware) installed and updated on each of the organizations workstations and servers?','<p>Malware (computer viruses and spyware) is one of the leading cause of data being stolen or breached. It is critical to have anti-malware installed on all systems including workstations, laptops, servers, etc. The anti-malware should be automatically updated with new definition files.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented anti-malware protection on all systems to prevent malicious intrusions.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have anti-malware on all systems to protect from malicious intrusions.</p>\r\n','RAQMALWARE'),
	(35,35,45,13,3,'Do workstations, laptops, and servers have inactivity timers to prevent unauthorized access to systems storing ePHI?','<p>Every system that contains ePHI should have an inactivity timeout that locks the screen or prevents access to the system. When a workforce member leaves their workstation another person could access ePHI without proper authorization. Inactivity timeouts prevents this from occurring.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented a procedure to have all systems setup with inactivity timers to prevent unauthorized access.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a procedure to have inactivity timers on all systems.</p>\r\n','RAQALIT'),
	(36,36,47,13,3,'Does the organization have a technical access control policy that is closely adhered to, to prevent unauthorized access to systems?','<p>The HIPAA Security Rule requires that technical access controls be implemented to protect ePHI. Technical access controls limit access to information. On a network share, technical access controls, may limit access to a patient folder to only those workforce members who are authorized. Other workforce members would not have the ability to access the information. The same is true for an EMR/EHR where technical access controls will limit who can access patient records. It is critical to implement strong technical access controls to protect ePHI. The HIPAA Security Rule states: Standard: Access control. Implement technical policies and procedures for electronic information systems that maintain electronic protected health information to allow access only to those persons or software programs that have been granted access rights.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented a technical access control policy to help prevent unauthorized access to systems and files, hackers, or intentional destruction of data.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have an implemented technical access control policy to facilitate specific security measures.</p>\r\n','RAQTAC'),
	(37,37,48,13,3,'Does the organization have a firewall in place on the network?','<p>Network firewalls protect organizations and ePHI from unauthorized access. Firewalls stop hackers and malware from entering a network. If an organization has an Internet connection such as a T-1, DSL or cable modem it is critical to have the connection protected by a firewall.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented secure firewalls to prevent outside intrusions on the network.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization has not implemented secure firewalls.</p>\r\n','RAQFW'),
	(38,38,12,3,1,'Does the organization have emergency operations procedures in place in the event of an emergency?','<p>The HIPAA Security Rule states the following as a requirement: (7)(i) Standard: Contingency plan. Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information. Emergency Mode Operations Plan (Required). Establish (and implement as needed) procedures to enable continuation of critical business processes for protection of the security of electronic protected health information while operating in emergency mode. When operating in an emergency mode it is important to protect ePHI.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented and tested a documented procedure for emergency operations in case of disasters such as floods, tornados, hurricanes or power failures. A documented process for handling a possible disaster.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a documented emergency operations plan in case of a disaster.</p>\r\n','RAQEOP'),
	(39,39,11,3,1,'Does the organization have hardware support contracts in place on all critical systems?','<p>The HIPAA Security Rule states the following as a requirement: (7)(i) Standard: Contingency plan. Establish (and implement as needed) policies and procedures for responding to an emergency or other occurrence (for example, fire, vandalism, system failure, and natural disaster) that damages systems that contain electronic protected health information. Disaster recovery plan (Required). Establish (and implement as needed) procedures to restore any loss of data. Having hardware support contracts in place will help in the event of a disaster. If equipment if damaged, hardware contracts can speed up the process of replacing the hardware.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has hardware support contracts in place in case of critical server/system failures due to hardware failures or caused by disaster.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have any hardware support contracts already in place.</p>\r\n','RAQHSC'),
	(40,40,24,8,2,'Does the organization protect PHI on monitors from unauthorized access?','<p>The HIPAA Security Rule states the following as a requirement: Standard: Workstation Use (Required). Implement policies and procedures that specify the proper functions to be performed, the manner in which those functions are to be performed, and the physical attributes of the surroundings of a specific workstation or class of workstation that can access electronic protected health information. Privacy screens can help prevent unauthorized access or viewing of ePHI. This is especially true when workstations that access ePHI are located in common areas that patients or visitors might access.</p>\r\n','<p>Answer &quot;YES&quot; if the organization uses privacy screens for monitors to protect ePHI from being displayed on the screens.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not use privacy screens on monitors.</p>\r\n','RAQPPM'),
	(41,41,21,7,2,'Does the organization track the movement of visitors and patients while they are in the organization\'s facility?','<p>The HIPAA Security Rule states the following as a requirement: Standard: Facility Access Control. Implement policies and procedures to limit physical access to its electronic information systems and the facility or facilities in which they are housed, while ensuring that properly authorized access is allowed. Implementation specific: Facility Security Plan (Addressable). Implement policies and procedures to safeguard the facility and the equipment therein from unauthorized physical access, tampering, and theft. Tracking visitors is a key part of a Facility Security Plan.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has a procedure implemented to track the movement of individuals inside the organization. I.E. security cameras or restricted access between rooms.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not track the movement of individuals inside the organization.</p>\r\n','RAQTVP'),
	(42,42,46,13,3,'Do all smartphones employ startup passwords and timeout locks?','<p>The HIPAA Security Rule states the following as a requirement: Standard: Person or Entity Authentication. Implement procedures to verify that a person or entity seeking access to electronic protected health information is the one claimed. If smartphones contain ePHI it is important to implement startup passwords and timeout locks to ensure that only authorized persons can access the contents of the smartphone. Due to the likelihood that smartphones may be lost or stolen, passwords can protect the contents of the smartphone.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has a procedure to implement startup passwords and timeout locks on all smartphones to help prevent against unauthorized access.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not implement a procedure to employ startup passwords and timeout locks on all smartphones.</p>\r\n','RAQSSP'),
	(43,43,27,8,2,'Do all servers use a Uninterrupted Power Supply (UPS)?','<p>The HIPAA Security Rule states that covered entities must ensure that ePHI is protected to ensure confidentiality, integrity, and availability. Installing a Uninterrupted Power Supply (UPS) can help ensure access (availability) to ePHI in the event of a power loss. A UPS should be installed on every system that contains ePHI as well as network equipment.</p>\r\n','<p>Answer &quot;YES&quot; if all systems that contain ePHI use a UPS (Uninterrupted Power Supply) in case of power failures to maintain system uptime.</p>\r\n\r\n<p>Answer &quot;NO&quot; if all systems that contain ePHI do not use a UPS in case of power failure.</p>\r\n','RAQUPS'),
	(44,44,16,6,1,'Are all workforce members required to go through security training?','<p>The HIPAA Security Rule Security Awareness and Training Standard states that an organization must implement a security awareness and training program for all members of its workforce (including management). The organization must also provide workforce members with periodic security reminders.</p>\r\n','<p>Answer &quot;YES&quot; if all workforce members are required to go through security training to increase their awareness of HIPAA security requirements and protecting ePHI.</p>\r\n\r\n<p>Answer &quot;NO&quot; if all workforce members are not required to go through HIPAA security training.</p>\r\n','RAQST'),
	(45,45,1,1,1,'Have you completed a Risk Assessment?','<p>The HIPAA Security Rule requires that a Risk Assessment be completed. The purpose of a Risk Assessment is to: identify where ePHI is located, the threats to ePHI, the risks to ePHI and determine safeguards to better protect ePHI.</p>\r\n','<p>Answer &#39;YES&#39; if the organization has previously completed a Risk Assessment.</p>\r\n\r\n<p>Answer &#39;NO&#39; if the organization has not completed a Risk Assessment.</p>\r\n','RAQRA1'),
	(46,46,2,1,1,'Have you implemented a Risk Management program?','<p>The HIPAA Security Rule requires that a Risk Management program be implemented. The Risk Management program evaluates and implements the recommended safeguards of a Risk Assessment to reduce risks and vulnerabilities to a reasonable and appropriate level. In addition, a Risk Management program periodically reviews system audit logs and activity. The HIPAA Security Rule further states that an organization should: Perform a periodic technical and nontechnical evaluation, based initially upon the standards implemented under this rule and subsequently, in response to environmental or operational changes affecting the security of [EPHI], that establishes the extent to which an entity&#39;s security polices and procedures meet the requirements of [the Security Rule].</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implemented a Risk Management program.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization has not implemented a Risk Management program or has not implemented a periodic review of system audit logs and activity or has not performed periodic technical and nontechnical evaluations.</p>\r\n','RAQRA2'),
	(47,47,3,1,1,'Does the organization have a Sanction Policy?','<p>The HIPAA Security Rule requires that a formal Sanction Policy be implemented to address situations where workforce members violate the HIPAA Security policies and procedures. Consequences for non-compliance could include retraining the workforce member who violated the policies and procedures, or perhaps terminating the individual if the violation is serious.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has implement and enforces a Sanction Policy for non-compliance with the HIPAA Security Rule.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization does not have a formal Sanction Policy or does not enforce the Sanction Policy.</p>\r\n','RAQSP'),
	(48,48,4,1,1,'Has the organization appointed a security officer?','<p>The HIPAA Security Rule requires that an organization appoint an individual that will be responsible for developing, implementing, maintaining and monitoring adherence to the HIPAA Security policies and procedures.</p>\r\n','<p>Answer &quot;YES&quot; if the organization has appointed a HIPAA security officer.</p>\r\n\r\n<p>Answer &quot;NO&quot; if the organization has not appointed a HIPAA security officer.</p>\r\n','RAQSO');

/*!40000 ALTER TABLE `risk_assessment_questions` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table users
# ------------------------------------------------------------

LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;

INSERT INTO `users` (`password`, `password_old`, `first_name`, `last_name`, `email`, `phone_number`, `cell_number`, `active`, `display_intro_video`, `tokenhash`, `last_login`, `group_id`, `client_id`, `partner_id`, `created`, `modified`, `email_validated`, `validation_code`, `moodle_token`)
VALUES
	('2bcacf6a3e2b07bd85b13304594621fe8b4b42b3',NULL,'admin','admin','admin@hipaa.com','','',1,1,'','2015-12-03 10:11:55',1,1,NULL,'2013-11-01 00:07:40','2015-12-03 10:11:55',1,'','2581a12b1223eeef11efccfa1d8ef38d');

/*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;

# moodle users view
CREATE VIEW `v_moodle_users` AS (select `users`.`id` AS `id`,concat('n',`users`.`id`) AS `moodle_id`,`users`.`email` AS `email`,`users`.`first_name` AS `first_name`,`users`.`last_name` AS `last_name`,`users`.`password` AS `password`,`users`.`moodle_token` AS `moodle_token`,`clients`.`moodle_course_id` AS `moodle_course_id`,`clients`.`name` AS `client_name` from (`users` left join `clients` on((`users`.`client_id` = `clients`.`id`))));

/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
